#!/bin/sh

install() {
    for var in "$@"; do
        [ ! -f ./"$var"/setup ] && echo "Cannot set up $var - setup script not found in $PWD/$var/setup" && return 1
        cd "$1"
        ./setup
        cd -
    done
}

echo "setting up dotfiles..."

for tool in */; do install "$tool"; done

ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"

ln -sf "$PWD/config/.cspell.json" "$HOME/.config/.cspell.json"

echo "successfully set up dotfiles!"
