#!/bin/sh

install() {
    for var in "$@"; do
        [ ! -f ./"$var"/setup ] && echo "Cannot set up $var - setup script not found in $PWD/$var/setup" && return 1
        cd "$1"
        ./setup
        cd -
    done
}

echo "setting up dotfiles..."

for tool in */; do install "$tool"; done

echo "successfully set up dotfiles!"
