#!/bin/sh

ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"

# copy tmuxifier layouts

# clear existing layouts if any
for file in "$HOME/.tmux/plugins/tmuxifier/layouts"/*; do
	rm $file
done

# install layouts from ./tmuxfier/layouts/*
mkdir -p "$HOME/.tmux/plugins/tmuxifier/layouts"
for file in "$PWD/tmuxifier/layouts"/*; do
	if [ -f "$file" ]; then
		ln -sf "$file" "$HOME/.tmux/plugins/tmuxifier/layouts/$(basename "$file")"
	fi
done
